"""classe table

Revision ID: 2a464bea63dc
Revises: dd4d2c87dffd
Create Date: 2019-12-14 13:13:37.243798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a464bea63dc'
down_revision = 'dd4d2c87dffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classe', sa.Column('tutor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classe', 'user', ['tutor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classe', type_='foreignkey')
    op.drop_column('classe', 'tutor_id')
    # ### end Alembic commands ###
